Update network.py
The Original gave an error  AttributeError: 'list' object has no attribute 'join' 
Changing to this  ' '.join(get_ip_addresses()) works as intended. Also works on an empty list.